version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/usr/src/app/app
    ports:
      - "4000:4000"
    # env_file:
      # - ./.env
    environment:
      REDIS_URL: redis://redis:6379
      PORT: 4000
    depends_on:
      - redis
  redis:
    image: "redis:alpine" 